export const JOURNAL_PROMPTS = [
  { id: 1, prompt: "What is one thing you did today that you're proud of?", theme: "strength" },
  { id: 2, prompt: "Name three things that made you smile this week.", theme: "gratitude" },
  { id: 3, prompt: "What is something you are really good at?", theme: "strength" },
  { id: 4, prompt: "If you could change one thing about today, what would it be?", theme: "today" },
  { id: 5, prompt: "Who is someone who has been kind to you recently? How did it make you feel?", theme: "kindness" },
  { id: 6, prompt: "What is a dream you have for your future?", theme: "dream" },
  { id: 7, prompt: "Describe a moment when you felt really brave.", theme: "strength" },
  { id: 8, prompt: "What is something beautiful you noticed today — big or small?", theme: "gratitude" },
  { id: 9, prompt: "If you could send a kind message to yourself, what would it say?", theme: "kindness" },
  { id: 10, prompt: "What is one thing you're looking forward to?", theme: "dream" },
  { id: 11, prompt: "Write about a time someone made you feel really good about yourself.", theme: "friendship" },
  { id: 12, prompt: "What is something hard you got through that you didn't think you could?", theme: "strength" },
  { id: 13, prompt: "What does a perfect day look like for you?", theme: "dream" },
  { id: 14, prompt: "Name one person you trust. What makes them special?", theme: "friendship" },
  { id: 15, prompt: "What is something you've learned this week?", theme: "today" },
  { id: 16, prompt: "Describe your favourite place in the world — real or imaginary.", theme: "dream" },
  { id: 17, prompt: "What are three words that describe you at your best?", theme: "strength" },
  { id: 18, prompt: "What always makes you feel better when you're sad?", theme: "today" },
  { id: 19, prompt: "Write about something that surprised you in a good way recently.", theme: "gratitude" },
  { id: 20, prompt: "What is a goal you have — even a tiny one — for next week?", theme: "dream" },
  { id: 21, prompt: "Who is someone you'd like to thank? What would you say to them?", theme: "kindness" },
  { id: 22, prompt: "What is one thing about yourself you really like?", theme: "strength" },
  { id: 23, prompt: "Describe a time when a friend helped you feel better.", theme: "friendship" },
  { id: 24, prompt: "What does being brave mean to you?", theme: "strength" },
  { id: 25, prompt: "Write about your favourite memory from the past year.", theme: "gratitude" },
  { id: 26, prompt: "If you had a superpower for just one day, what would it be and why?", theme: "dream" },
  { id: 27, prompt: "What does a good friend look like to you?", theme: "friendship" },
  { id: 28, prompt: "Name something small that brought you joy today.", theme: "gratitude" },
  { id: 29, prompt: "If you could write a letter to your future self, what would you say?", theme: "dream" },
  { id: 30, prompt: "What is one thing you want others to know about you?", theme: "kindness" },
  { id: 31, prompt: "What has been the most challenging part of your week? How did you handle it?", theme: "today" },
  { id: 32, prompt: "Write about someone you admire and what makes them special.", theme: "friendship" },
];
