export const MOTIVATION_CARDS = [
  // Courage
  { id: 1, quote: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne", theme: "courage" },
  { id: 2, quote: "Courage doesn't always roar. Sometimes it's the quiet voice at the end of the day saying, 'I will try again tomorrow.'", author: "Mary Anne Radmacher", theme: "courage" },
  { id: 3, quote: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", theme: "courage" },
  { id: 4, quote: "It takes courage to grow up and become who you really are.", author: "E.E. Cummings", theme: "courage" },
  { id: 5, quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", theme: "courage" },
  { id: 6, quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt", theme: "courage" },
  { id: 7, quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", theme: "courage" },
  { id: 8, quote: "Each step you take reveals a new horizon. You have strength — go forward.", author: "Unknown", theme: "courage" },
  { id: 9, quote: "The bravest thing you can do is keep going when giving up feels easy.", author: "Unknown", theme: "courage" },
  { id: 10, quote: "You were given this life because you are strong enough to live it.", author: "Unknown", theme: "courage" },

  // Resilience
  { id: 11, quote: "Stars can't shine without darkness.", author: "Unknown", theme: "resilience" },
  { id: 12, quote: "Fall seven times, stand up eight.", author: "Japanese Proverb", theme: "resilience" },
  { id: 13, quote: "Rock bottom became the solid foundation on which I rebuilt my life.", author: "J.K. Rowling", theme: "resilience" },
  { id: 14, quote: "The human spirit is stronger than anything that can happen to it.", author: "C.C. Scott", theme: "resilience" },
  { id: 15, quote: "Sometimes you don't realize your own strength until you come face to face with your greatest weakness.", author: "Susan Gale", theme: "resilience" },
  { id: 16, quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", theme: "resilience" },
  { id: 17, quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey", theme: "resilience" },
  { id: 18, quote: "You are allowed to be both a masterpiece and a work in progress simultaneously.", author: "Sophia Bush", theme: "resilience" },
  { id: 19, quote: "Every storm runs out of rain.", author: "Maya Angelou", theme: "resilience" },
  { id: 20, quote: "She stood in the storm, and when the wind did not blow her away, she adjusted her sails.", author: "Elizabeth Edwards", theme: "resilience" },

  // Kindness
  { id: 21, quote: "You don't have to be perfect to be amazing.", author: "Unknown", theme: "kindness" },
  { id: 22, quote: "Be kind, for everyone you meet is fighting a hard battle.", author: "Ian Maclaren", theme: "kindness" },
  { id: 23, quote: "A little kindness from person to person is better than a vast love for all humankind.", author: "Richard Dehmel", theme: "kindness" },
  { id: 24, quote: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop", theme: "kindness" },
  { id: 25, quote: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain", theme: "kindness" },
  { id: 26, quote: "Carry out a random act of kindness — you cannot do a kindness too soon.", author: "Ralph Waldo Emerson", theme: "kindness" },
  { id: 27, quote: "One of the most important things you can do on this earth is to let people know they are not alone.", author: "Shannon L. Alder", theme: "kindness" },
  { id: 28, quote: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", author: "Buddha", theme: "kindness" },
  { id: 29, quote: "Be the reason someone smiles today.", author: "Unknown", theme: "kindness" },
  { id: 30, quote: "Kindness makes you the most beautiful person in the world, no matter what you look like.", author: "Unknown", theme: "kindness" },

  // Growth
  { id: 31, quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", theme: "growth" },
  { id: 32, quote: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar", theme: "growth" },
  { id: 33, quote: "The only way to do great work is to love what you do.", author: "Steve Jobs", theme: "growth" },
  { id: 34, quote: "Success is not final, failure is not fatal — it is the courage to continue that counts.", author: "Winston Churchill", theme: "growth" },
  { id: 35, quote: "Every day is a chance to be better than yesterday.", author: "Unknown", theme: "growth" },
  { id: 36, quote: "Small steps every day add up to big changes.", author: "Unknown", theme: "growth" },
  { id: 37, quote: "Your only limit is you.", author: "Unknown", theme: "growth" },
  { id: 38, quote: "Don't watch the clock — do what it does. Keep going.", author: "Sam Levenson", theme: "growth" },
  { id: 39, quote: "Mistakes are proof that you're trying.", author: "Unknown", theme: "growth" },
  { id: 40, quote: "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don't belong.", author: "Mandy Hale", theme: "growth" },

  // Hope
  { id: 41, quote: "Every day may not be good, but there is something good in every day.", author: "Alice Morse Earle", theme: "hope" },
  { id: 42, quote: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo", theme: "hope" },
  { id: 43, quote: "Hope is being able to see that there is light despite all of the darkness.", author: "Desmond Tutu", theme: "hope" },
  { id: 44, quote: "Once you choose hope, anything is possible.", author: "Christopher Reeve", theme: "hope" },
  { id: 45, quote: "Tomorrow is always fresh with no mistakes in it.", author: "L.M. Montgomery", theme: "hope" },
  { id: 46, quote: "Keep your face always toward the sunshine — and shadows will fall behind you.", author: "Walt Whitman", theme: "hope" },
  { id: 47, quote: "There are far, far better things ahead than any we leave behind.", author: "C.S. Lewis", theme: "hope" },
  { id: 48, quote: "When you can't find the sunshine, be the sunshine.", author: "Unknown", theme: "hope" },
  { id: 49, quote: "It always seems impossible until it's done.", author: "Nelson Mandela", theme: "hope" },
  { id: 50, quote: "Sometimes the smallest step in the right direction ends up being the biggest step of your life.", author: "Unknown", theme: "hope" },

  // Friendship
  { id: 51, quote: "A real friend is one who walks in when the rest of the world walks out.", author: "Walter Winchell", theme: "friendship" },
  { id: 52, quote: "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'", author: "C.S. Lewis", theme: "friendship" },
  { id: 53, quote: "You are never alone when you have your own heart as your friend.", author: "Unknown", theme: "friendship" },
  { id: 54, quote: "True friendship comes when the silence between two people is comfortable.", author: "David Tyson", theme: "friendship" },
  { id: 55, quote: "The most beautiful discovery true friends make is that they can grow separately without growing apart.", author: "Elisabeth Foley", theme: "friendship" },
  { id: 56, quote: "A good friend knows all your stories. A best friend helped you write them.", author: "Unknown", theme: "friendship" },
  { id: 57, quote: "In the cookie of life, friends are the chocolate chips.", author: "Salman Rushdie", theme: "friendship" },
  { id: 58, quote: "Side by side or miles apart, good friends are always close to the heart.", author: "Unknown", theme: "friendship" },
  { id: 59, quote: "You are someone's reason to smile today. Don't forget that.", author: "Unknown", theme: "friendship" },
  { id: 60, quote: "You matter. You are enough. You are worthy of kindness — especially from yourself.", author: "Unknown", theme: "kindness" },
  { id: 61, quote: "What you are is a miracle. What you're becoming is even more beautiful.", author: "Unknown", theme: "growth" },
  { id: 62, quote: "The sun will rise and we will try again.", author: "Twenty One Pilots", theme: "hope" },
  { id: 63, quote: "Even on your worst day, you are someone's everything.", author: "Unknown", theme: "friendship" },
  { id: 64, quote: "Your story isn't over yet.", author: "Unknown", theme: "resilience" },
];
